worker_processes auto;
worker_rlimit_nofile 65535;

events {
    worker_connections 65535;
}

http {
    upstream chat_gateway {
        ip_hash;
        server chat-gateway:4001;
    }

    upstream chat_worker {
        server chat-worker:4002;
    }

    server {
        listen 4001;
        location / {
            proxy_pass http://chat_gateway;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 4002;
        location / {
            proxy_pass http://chat_worker;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
